# This file is part of the Jsonify.
#
# (c) 2021 airSlate <support@airslate.com>
#
# For the full copyright and license information, please view
# the LICENSE file that was distributed with this source code.

version: '3.7'


services:
  app:
    image: airslate/jsonify:latest
    build:
      context: .
    command: dev
    environment:
      PYTHONDONTWRITEBYTECODE: 1
      PYTHONUNBUFFERED: 1
    ports:
      - 5001:5000
    volumes:
      - .:/usr/src/app
    depends_on:
      - db

  db:
    image: mariadb:10.5.8
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: 'yes'
      MYSQL_DATABASE: jsonify
      MYSQL_USER: jsonify
      MYSQL_PASSWORD: jsonify
    ports:
      - 3309:3306
    volumes:
      - jsonify_db:/var/lib/mysql

volumes:
  jsonify_db:
